name: iqraa
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.2
  # ios
  cupertino_icons: ^1.0.6

  # windows
  fluent_ui: ^4.8.7

  # linux
  yaru: ^4.1.0

  # macos
  macos_ui: ^2.0.5

  # dependency injection
  get_it: ^7.7.0
  injectable: ^2.4.1

  # state management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  mockito: ^5.4.4
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  custom_lint: ^0.6.4
  build_runner: ^2.4.9
  injectable_generator: ^2.4.1
  test: ^1.24.9
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true